language: python
python:
  - '3.4'
services:
  - elasticsearch
install:
  - travis_retry python setup.py install
  - travis_retry pip install -r requirements-dev.txt
script:
  - py.test tests/
sudo: false
